# Generated by Django 4.1 on 2024-06-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.FileField(upload_to='obj_desc/')),
                ('img', models.ImageField(upload_to='obj_img/')),
                ('registration_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObjText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('open', models.CharField(max_length=7)),
                ('objId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object.objectdesc')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
        ),
    ]
