# Generated by Django 4.1 on 2023-12-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpost',
            name='eunRotation',
        ),
        migrations.AddField(
            model_name='outpost',
            name='eunRotationW',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='outpost',
            name='eunRotationX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='outpost',
            name='eunRotationY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='outpost',
            name='eunRotationZ',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='outpost',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
