# Generated by Django 4.2.2 on 2023-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
