# Generated by Django 4.2.2 on 2023-12-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0002_alter_outpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
