# Generated by Django 4.1 on 2023-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0002_remove_outpost_eunrotation_outpost_eunrotationw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
