# Generated by Django 4.1 on 2024-01-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0003_alter_outpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
