# Generated by Django 4.2.2 on 2024-05-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='correctQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gyeongbokgung',
            fields=[
                ('quizId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('eunRotationX', models.FloatField(default=0.0)),
                ('eunRotationY', models.FloatField(default=0.0)),
                ('eunRotationZ', models.FloatField(default=0.0)),
                ('eunRotationW', models.FloatField(default=0.0)),
                ('content', models.TextField()),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GyeongbokgungStamp', models.BooleanField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuizUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forQuizCount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.correctquiz')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
        ),
        migrations.AddField(
            model_name='correctquiz',
            name='quizId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.gyeongbokgung'),
        ),
    ]
