# Generated by Django 4.1 on 2024-06-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gyeongbokgung',
            fields=[
                ('quizId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('eunRotationX', models.FloatField(default=0.0)),
                ('eunRotationY', models.FloatField(default=0.0)),
                ('eunRotationZ', models.FloatField(default=0.0)),
                ('eunRotationW', models.FloatField(default=0.0)),
                ('content', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GyeongbokgungStamp', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='correctQuizInGyeongbokgung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.gyeongbokgung')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
            options={
                'unique_together': {('quizId', 'userId')},
            },
        ),
    ]
