# Generated by Django 4.2.2 on 2024-05-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('quiz', '0002_alter_gyeongbokgung_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='correctQuizInGyeongbokgung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.gyeongbokgung')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
            options={
                'unique_together': {('quizId', 'userId')},
            },
        ),
        migrations.RemoveField(
            model_name='quizuser',
            name='forQuizCount',
        ),
        migrations.RemoveField(
            model_name='quizuser',
            name='userId',
        ),
        migrations.AlterField(
            model_name='stamp',
            name='GyeongbokgungStamp',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='correctQuiz',
        ),
        migrations.DeleteModel(
            name='QuizUser',
        ),
    ]
