# Generated by Django 4.1 on 2024-01-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
